server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie  #用于指定注册到Eureka Server上的应用名称

eureka:
  client:
    serviceUrl:
      defaultZooe: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    perfer-ip-address: true #将自己IP注册到Eureka Server


